name: ShulkerBoxPlus
version: 1.0.0
main: jp.iceserver.shulkerboxplus.ShulkerBoxPlus
api-version: 1.18
authors: [ Minidon ]
description: シュルカーボックスを手に持って右クリックすると開けるようになるプラグイン
website: https://github.com/IceServerLab/ShulkerBoxPlus
